<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="SQA-CRS-021" name="rebill.testngRebillSlow" tests="65" failures="2" timestamp="05 May 2020 20:17:34 GMT" time="2687.996" errors="15">
  <testcase name="testMethod2" time="62.669" classname="rebill.testngRebillSlow">
    <skipped/>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod2" time="49.698" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="110.159" classname="rebill.testngRebillSlow">
    <skipped/>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod4" time="0.160" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.153" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="61.176" classname="rebill.testngRebillSlow">
    <error type="org.openqa.selenium.WebDriverException" message="unknown error: DevToolsActivePort file doesn&#039;t exist
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.25 seconds
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:25:48&#039;
System info: host: &#039;SQA-CRS-021&#039;, ip: &#039;10.255.251.244&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;x86&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_212&#039;
Driver info: driver.version: ChromeDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.25 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'SQA-CRS-021', ip: '10.255.251.244', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_212'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at rebill.testngRebillSlow.testMethod2(testngRebillSlow.java:392)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod1" time="50.806" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="0.280" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.191" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="0.244" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.156" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.183" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod4" time="51.756" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.157" classname="rebill.testngRebillSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod3" time="0.173" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="61.207" classname="rebill.testngRebillSlow">
    <error type="org.openqa.selenium.WebDriverException" message="unknown error: DevToolsActivePort file doesn&#039;t exist
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.24 seconds
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:25:48&#039;
System info: host: &#039;SQA-CRS-021&#039;, ip: &#039;10.255.251.244&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;x86&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_212&#039;
Driver info: driver.version: ChromeDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.24 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'SQA-CRS-021', ip: '10.255.251.244', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_212'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at rebill.testngRebillSlow.testMethod2(testngRebillSlow.java:392)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod2" time="232.070" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="51.001" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod4" time="48.988" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.125" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="48.882" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="230.743" classname="rebill.testngRebillSlow">
    <skipped/>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod1" time="0.109" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="73.288" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod4" time="73.803" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="74.533" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="60.096" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="49.844" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod4" time="55.740" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod4" time="51.416" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.117" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.157" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="49.883" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="0.235" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod4" time="48.347" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="71.353" classname="rebill.testngRebillSlow">
    <failure type="java.lang.AssertionError" message="Failed at Drop Down">
      <![CDATA[java.lang.AssertionError: Failed at Drop Down
	at org.testng.Assert.fail(Assert.java:93)
	at rebill.testngRebillSlow.doRebill(testngRebillSlow.java:740)
	at rebill.testngRebillSlow.testMethod2(testngRebillSlow.java:397)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod3" time="0.248" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod4" time="52.927" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="54.544" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="0.231" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.179" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.119" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod4" time="53.838" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.467" classname="rebill.testngRebillSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod3" time="72.084" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod4" time="0.265" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.204" classname="rebill.testngRebillSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="0.325" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="49.819" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="70.152" classname="rebill.testngRebillSlow">
    <failure type="java.lang.AssertionError" message="Failed at Drop Down">
      <![CDATA[java.lang.AssertionError: Failed at Drop Down
	at org.testng.Assert.fail(Assert.java:93)
	at rebill.testngRebillSlow.doRebill(testngRebillSlow.java:740)
	at rebill.testngRebillSlow.testMethod2(testngRebillSlow.java:397)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod4" time="0.254" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="0.172" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="0.230" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="77.534" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="64.307" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="0.425" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="50.710" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod2" time="98.364" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="50.585" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.231" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="217.783" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.187" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 30 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod4" time="50.696" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod3" time="51.094" classname="rebill.testngRebillSlow"/>
  <testcase name="testMethod1" time="0.124" classname="rebill.testngRebillSlow">
    <error type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at rebill.testngRebillSlow.writeToExcel(testngRebillSlow.java:1054)
	at rebill.testngRebillSlow.testMethod1(testngRebillSlow.java:310)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.DeflaterOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at java.util.zip.ZipOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:531)
	... 29 more
]]>
    </error>
  </testcase> <!-- testMethod1 -->
</testsuite> <!-- rebill.testngRebillSlow -->
